---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: win-npd
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npd
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      serviceAccountName: win-npd
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: npd
          image:  ghcr.io/marosset/aks-windows-npd:v0.0.1
          imagePullPolicy: Always
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - name: kube-dir
              mountPath: C:\k
      volumes:
      - name:  kube-dir
        hostPath:
          path: C:\k
