apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: win-npd
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/status"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: win-npd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: win-npd
subjects:
- kind: ServiceAccount
  name: win-npd
  namespace: kube-system
